name: fluffychat
description: Chat with your friends.
publish_to: none
version: 0.28.1+0

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  famedlysdk:
    git:
      url: https://gitlab.com/famedly/famedlysdk.git
      ref: main
  fcm_shared_isolate:
    git:
      url: https://gitlab.com/famedly/libraries/fcm_shared_isolate.git
      ref: ios
  flutter_matrix_html:
    git:
      url: https://github.com/Sorunome/flutter_matrix_html.git
      ref: 6b6a850fcfc3b0a3e88a3dd6beb79eda3acac853
  native_imaging:
    git:
      url: https://gitlab.com/famedly/libraries/native_imaging.git
      ref: master
  unifiedpush:
    git:
      url: https://github.com/UnifiedPush/flutter-connector.git
      ref: 8edc09a87d726d912926ac612e209573452c1273
  ffi: ^0.1.3
  adaptive_dialog: ^0.9.3
  adaptive_page_layout: ^0.2.1
  adaptive_theme: ^1.1.0
  android_path_provider: ^0.1.1
  cached_network_image: ^2.5.0
  circular_check_box: ^1.0.4
  cupertino_icons: any
  email_validator: ^1.0.6
  emoji_picker: ^0.1.0
  file_picker_cross: ^4.2.8
  firebase_messaging: any
  flutter_app_lock: ^1.4.0+1
  flutter_blurhash: ^0.5.0
  flutter_cache_manager: ^2.1.1
  flutter_local_notifications: ^3.0.3
  flutter_olm: ^1.1.1
  flutter_screen_lock: ^1.2.6
  flutter_secure_storage: ^3.3.5
  flutter_slidable: ^0.5.7
  flutter_sound_lite: ^7.5.3+1
  flutter_svg: ^0.19.3
  flutter_typeahead: ^2.0.0
  future_loading_dialog: ^0.1.2
  http: ^0.12.2
  image_picker: ^0.6.7+21
  intl: any
  localstorage: ^3.0.6+9
  matrix_link_text: ^0.3.2
  mime_type: ^0.3.2
  moor: ^3.4.0
  open_file: ^3.0.3
  open_noti_settings: ^0.0.4
  package_info: ^0.4.3+2
  path_provider: ^1.6.27
  permission_handler: ^5.0.1+1
  provider: ^4.3.3
  random_string: ^2.1.0
  receive_sharing_intent: ^1.4.3
  scroll_to_index: ^1.0.6
  sentry: ">=3.0.0 <4.0.0"
  share: ^0.6.5+4
  sqflite: ^1.3.2+2
  sqlite3: ^0.1.8
  swipe_to_action: ^0.1.0
  universal_html: ^1.2.4
  url_launcher: ^5.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  dapackages: ^1.4.0

  pedantic: ^1.9.2

# The flutter_maths version of flutter_matrix_html is weird and conflicts with a few of our packages.
# So, we have to force-override the dependencies to work out.
dependency_overrides:
  provider: ^4.3.3
  flutter_svg: ^0.19.3
  # Was actually brought in via fcm packages and flutter_matrix_html
  quiver: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/sounds/
    - assets/js/
    - assets/js/package/

  fonts:
    - family: NotoEmoji
      fonts:
        - asset: fonts/NotoEmoji/NotoColorEmoji.ttf
    - family: OpenSans
      fonts:
        - asset: fonts/Open_Sans/OpenSans-Regular.ttf
        - asset: fonts/Open_Sans/OpenSans-Italic.ttf
          style: italic
        - asset: fonts/Open_Sans/OpenSans-Bold.ttf
          weight: 700
        - asset: fonts/Open_Sans/OpenSans-BoldItalic.ttf
          weight: 700
          style: italic
